<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CALCULO DE METAS</title>
</head>
<body>
    <h1>CALCULO DE METAS
    </h1>
    <form action="processar_dados.php" method="POST">
        <label for="nome">Nome do funcionario</label>
        <input type="text" id="nome" name="nome" placeholder="Digite seu nome aqui" required>
        <br><br>
      
    </form>
    <form action="processar_dados.php" method="POST">
        <label for="nome">semana 1</label>
        <input type="text" id="nome" name="nome" placeholder="Digite seu nome aqui" required>
        <br><br>
       
    </form>
    <form action="processar_dados.php" method="POST">
        <label for="nome">semana 2</label>
        <input type="text" id="nome" name="nome" placeholder="Digite seu nome aqui" required>
        <br><br>
        
    </form>
    <form action="processar_dados.php" method="POST">
        <label for="nome">semana 3</label>
        <input type="text" id="nome" name="nome" placeholder="Digite seu nome aqui" required>
        <br><br>
      
    </form>
    <form action="processar_dados.php" method="POST">
        <label for="nome">semana 4</label>
        <input type="text" id="nome" name="nome" placeholder="Digite seu nome aqui" required>
        <br><br>
        
    </form>
    <form action="processar_dados.php" method="POST">
        <label for="nome">Valor Mensal</label>
        <input type="text" id="nome" name="nome" placeholder="Digite seu nome aqui" required>
        <br><br>
        <input type="submit" value="Enviar">
    </form>
</body>
</html>
  
</body>
</html>